\! echo 'bikes' ;
select count(*) from bikes ;
\! echo '';
\! echo 'brands';
select count(*) from brands  ;
\! echo '';
\! echo 'categories';
select count(*) from categories ;
\! echo '';
\! echo 'orderitems';
select count(*) from orderitems ;
\! echo '';
\! echo 'orders';   
select count(*) from orders ;
\! echo '';
\! echo 'staffs';
select count(*) from staffs ;
\! echo '';
\! echo 'stocks';
select count(*) from stocks ;
\! echo '';
\! echo 'stores';
select count(*) from stores ;