#!/bin/bash
set -eo pipefail

<<com
jq -c '.stack[]' stackConfig.json | while read i; do
   echo "$i.env"
 done

| map(select(.EnvironmentName == "AMI"))

.[] | select(.KVs[] | .Key == "animal" and .Value == "lion")

readarray -t projects < <( jq -c '.[] | select(.env) | .env | map(select(.EnvironmentName == "AMI" ))' stackConfig.json )
 for i in "${projects[@]}"; do
    echo $i['EnvironmentName']
 done

 --arg prefix "ParameterKey="

envt=AMI \
jq -r  ' .[] | select(.env) | .env | map(select(.EnvironmentName == env.envt ))[]  '  \
stackConfig.json

com



aws rds  describe-db-instances --profile todd | jq '.DBInstances[] | select(.DBName | startswith("ami")) | .Endpoint.Address

 aws  cognito-idp list-user-pools --max-results 5 --profile todd | jq '.UserPools[] | select(.Name=="ami-bikes-apigateway") |.Id'


 aws cognito-idp list-user-pool-clients  --user-pool-id=us-east-2_rs8QC7V8B --profile todd
{
    "UserPoolClients": [
        {
            "ClientId": "77eqq3m9gkiqikuo5q3qkuepf4",
            "UserPoolId": "us-east-2_rs8QC7V8B",
            "ClientName": "ami-bikes-apigateway"
        }
    ]
}


 ./getMetaData.sh > ~/files/ec2details^C
[ec2-user@ip-10-192-20-221 scripts]$ cat getMetaData.sh


TOKEN=`curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600"`
INSTANCEID=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-id`
ENVHOSTTYPE=`aws ec2 describe-tags --filters "Name=key,Values=ENVHOSTTYPE" | jq -r --arg jq_iid $INSTANCEID '.Tags[] | select(.Key == "ENVHOSTTYPE" and .ResourceId == $jq_iid).Value '`
INSTANCETYPE=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/instance-type`
INSTANCEPROFILEARN=`curl -H "X-aws-ec2-metadata-token: $TOKEN" -v http://169.254.169.254/latest/meta-data/iam/info | jq -r '.InstanceProfileArn'`
echo 'INSTANCEID: ' $INSTANCEID
echo 'EANVHOSTTYPE: '  $ENVHOSTTYPE
echo 'INSTANCETYPE: ' $INSTANCETYPE
echo 'INSTANCEPROFILEARN: ' $INSTANCEPROFILEARN


